"""add_system_config_and_alerts

Revision ID: b13bd82eabba
Revises: 003_continuous_aggregates
Create Date: 2025-11-28 18:22:21.892928+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13bd82eabba'
down_revision = '003_continuous_aggregates'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_enabled'), 'alert_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('requires_restart', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_config_category'), 'system_config', ['category'], unique=False)
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=False)
    op.drop_index(op.f('idx_active_instruments_only'), table_name='instruments', postgresql_where='(is_active = true)', postgresql_include=['symbol', 'exchange', 'segment'])
    op.drop_index(op.f('idx_market_snapshots_symbol_time_covering'), table_name='market_snapshots', postgresql_include=['ltp', 'volume', 'oi'])
    op.drop_index(op.f('idx_market_snapshots_timestamp_brin'), table_name='market_snapshots', postgresql_with={'pages_per_range': '128'}, postgresql_using='brin')
    op.drop_index(op.f('idx_options_active_ce'), table_name='option_contracts', postgresql_where="((option_type)::text = 'CE'::text)")
    op.drop_index(op.f('idx_options_active_pe'), table_name='option_contracts', postgresql_where="((option_type)::text = 'PE'::text)")
    op.drop_index(op.f('idx_options_lookup_covering'), table_name='option_contracts', postgresql_include=['ltp', 'volume', 'oi', 'iv'])
    op.drop_index(op.f('idx_options_timestamp_brin'), table_name='option_contracts', postgresql_with={'pages_per_range': '128'}, postgresql_using='brin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_options_timestamp_brin'), 'option_contracts', ['timestamp'], unique=False, postgresql_with={'pages_per_range': '128'}, postgresql_using='brin')
    op.create_index(op.f('idx_options_lookup_covering'), 'option_contracts', ['symbol_id', 'expiry', 'option_type', 'strike_price'], unique=False, postgresql_include=['ltp', 'volume', 'oi', 'iv'])
    op.create_index(op.f('idx_options_active_pe'), 'option_contracts', ['symbol_id', 'timestamp'], unique=False, postgresql_where="((option_type)::text = 'PE'::text)")
    op.create_index(op.f('idx_options_active_ce'), 'option_contracts', ['symbol_id', 'timestamp'], unique=False, postgresql_where="((option_type)::text = 'CE'::text)")
    op.create_index(op.f('idx_market_snapshots_timestamp_brin'), 'market_snapshots', ['timestamp'], unique=False, postgresql_with={'pages_per_range': '128'}, postgresql_using='brin')
    op.create_index(op.f('idx_market_snapshots_symbol_time_covering'), 'market_snapshots', ['symbol_id', sa.literal_column('timestamp DESC')], unique=False, postgresql_include=['ltp', 'volume', 'oi'])
    op.create_index(op.f('idx_active_instruments_only'), 'instruments', ['symbol_id'], unique=False, postgresql_where='(is_active = true)', postgresql_include=['symbol', 'exchange', 'segment'])
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_index(op.f('ix_system_config_category'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_enabled'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
