"""Add community tables

Revision ID: 2a40ea397f7b
Revises: 20251202_1109_phase_2_analytics, add_trade_date_001
Create Date: 2026-01-03 14:29:40.255834+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a40ea397f7b'
down_revision = ('20251202_1109_phase_2_analytics', 'add_trade_date_001')
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('room_type', sa.Enum('MARKET_OUTLOOK', 'SIGNAL_DISCUSSION', 'TRADE_BREAKDOWN', 'STRATEGY_INSIGHTS', 'FEEDBACK', name='roomtype'), nullable=False),
    sa.Column('is_read_only', sa.Boolean(), nullable=False),
    sa.Column('min_reputation_to_post', sa.Integer(), nullable=False),
    sa.Column('post_cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('allowed_roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_community_rooms_active_type', 'community_rooms', ['is_active', 'room_type'], unique=False)
    op.create_index(op.f('ix_community_rooms_id'), 'community_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_community_rooms_is_active'), 'community_rooms', ['is_active'], unique=False)
    op.create_index(op.f('ix_community_rooms_room_type'), 'community_rooms', ['room_type'], unique=False)
    op.create_index(op.f('ix_community_rooms_slug'), 'community_rooms', ['slug'], unique=True)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('trade_type', sa.Enum('CE', 'PE', 'FUT', name='tradetype'), nullable=True),
    sa.Column('trade_reason', sa.Enum('OI_BUILDUP', 'OI_UNWINDING', 'PCR_SHIFT', 'IV_CHANGE', 'SUPPORT_RESISTANCE', 'PATTERN_BREAKOUT', 'REVERSAL_SIGNAL', 'NEWS_EVENT', 'HEDGING', 'OTHER', name='tradereason'), nullable=True),
    sa.Column('trade_explanation', sa.Text(), nullable=True),
    sa.Column('screenshot_url', sa.Text(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('downvotes >= 0', name='chk_downvotes_nonneg'),
    sa.CheckConstraint('upvotes >= 0', name='chk_upvotes_nonneg'),
    sa.ForeignKeyConstraint(['author_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_post_id'], ['community_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['community_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_community_posts_author', 'community_posts', ['author_id', 'created_at'], unique=False)
    op.create_index('idx_community_posts_pinned', 'community_posts', ['room_id', 'is_pinned', 'created_at'], unique=False)
    op.create_index('idx_community_posts_room_created', 'community_posts', ['room_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_community_posts_signal', 'community_posts', ['signal_id'], unique=False)
    op.create_index(op.f('ix_community_posts_author_id'), 'community_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_posts_created_at'), 'community_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_index(op.f('ix_community_posts_is_deleted'), 'community_posts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_community_posts_parent_post_id'), 'community_posts', ['parent_post_id'], unique=False)
    op.create_index(op.f('ix_community_posts_room_id'), 'community_posts', ['room_id'], unique=False)
    op.create_index(op.f('ix_community_posts_signal_id'), 'community_posts', ['signal_id'], unique=False)
    op.create_table('feature_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PLANNED', 'IN_PROGRESS', 'COMPLETED', 'DECLINED', name='featurestatus'), nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feature_status_votes', 'feature_requests', ['status', sa.literal_column('vote_count DESC')], unique=False)
    op.create_index(op.f('ix_feature_requests_author_id'), 'feature_requests', ['author_id'], unique=False)
    op.create_index(op.f('ix_feature_requests_created_at'), 'feature_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_feature_requests_id'), 'feature_requests', ['id'], unique=False)
    op.create_index(op.f('ix_feature_requests_status'), 'feature_requests', ['status'], unique=False)
    op.create_index(op.f('ix_feature_requests_vote_count'), 'feature_requests', ['vote_count'], unique=False)
    op.create_table('user_reputation',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('helpful_votes', sa.Integer(), nullable=False),
    sa.Column('trade_accuracy', sa.Float(), nullable=False),
    sa.Column('total_trades_shared', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('verified_trader', sa.Boolean(), nullable=False),
    sa.Column('community_role', sa.Enum('USER', 'VERIFIED_TRADER', 'ANALYST', 'ADMIN', name='communityrole'), nullable=False),
    sa.Column('posting_cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('last_post_at', sa.DateTime(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_reputation_score', 'user_reputation', [sa.literal_column('reputation_score DESC')], unique=False)
    op.create_index('idx_reputation_verified', 'user_reputation', ['verified_trader', sa.literal_column('reputation_score DESC')], unique=False)
    op.create_index(op.f('ix_user_reputation_reputation_score'), 'user_reputation', ['reputation_score'], unique=False)
    op.create_index(op.f('ix_user_reputation_verified_trader'), 'user_reputation', ['verified_trader'], unique=False)
    op.create_table('community_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reaction_type', sa.Enum('UPVOTE', 'DOWNVOTE', 'CONFIRM', 'DISAGREE', 'NEUTRAL', name='reactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_reaction_post_user')
    )
    op.create_index('idx_reaction_post_type', 'community_reactions', ['post_id', 'reaction_type'], unique=False)
    op.create_index(op.f('ix_community_reactions_id'), 'community_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_community_reactions_post_id'), 'community_reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_reactions_user_id'), 'community_reactions', ['user_id'], unique=False)
    op.create_table('feature_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_request_id'], ['feature_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_request_id', 'user_id', name='uq_feature_vote_user')
    )
    op.create_index(op.f('ix_feature_votes_feature_request_id'), 'feature_votes', ['feature_request_id'], unique=False)
    op.create_index(op.f('ix_feature_votes_id'), 'feature_votes', ['id'], unique=False)
    op.create_index(op.f('ix_feature_votes_user_id'), 'feature_votes', ['user_id'], unique=False)
    op.create_table('signal_threads',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('market_snapshot', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.Enum('PENDING', 'WIN', 'LOSS', 'NEUTRAL', name='signaloutcome'), nullable=False),
    sa.Column('outcome_pnl', sa.Float(), nullable=True),
    sa.Column('bullish_reactions', sa.Integer(), nullable=False),
    sa.Column('bearish_reactions', sa.Integer(), nullable=False),
    sa.Column('neutral_reactions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index('idx_signal_thread_outcome', 'signal_threads', ['outcome', 'created_at'], unique=False)
    op.create_index(op.f('ix_signal_threads_outcome'), 'signal_threads', ['outcome'], unique=False)
    op.create_index(op.f('ix_signal_threads_post_id'), 'signal_threads', ['post_id'], unique=False)
    op.create_index(op.f('ix_signal_threads_signal_id'), 'signal_threads', ['signal_id'], unique=False)
    op.drop_index(op.f('ix_ticket_messages_id'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_trading_instruments_id'), table_name='trading_instruments')
    op.drop_index(op.f('ix_trading_instruments_symbol'), table_name='trading_instruments')
    op.drop_table('trading_instruments')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_purpose'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_system_configs_category'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_ticket_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('ISSUE', 'MARKET_DATA', 'FEATURE_REQUEST', 'BILLING', 'OTHER', name='ticketcategory'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name='support_tickets_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='support_tickets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_id'), 'support_tickets', ['ticket_id'], unique=True)
    op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('API', 'CACHE', 'SECURITY', 'TRADING', 'UI', 'SYSTEM', 'FEATURES', name='configcategory'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_sensitive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fallback_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['app_users.id'], name=op.f('system_configs_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_configs_pkey'))
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_index(op.f('ix_system_configs_category'), 'system_configs', ['category'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'TRADE', 'PRICE', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sound_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('extra_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_purpose'), 'notifications', ['user_id', 'purpose'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_created'), 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('trading_instruments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('segment', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('lot_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tick_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('strike_interval', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('strikes_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('trading_instruments_pkey'))
    )
    op.create_index(op.f('ix_trading_instruments_symbol'), 'trading_instruments', ['symbol'], unique=True)
    op.create_index(op.f('ix_trading_instruments_id'), 'trading_instruments', ['id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('enable_in_app', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_push', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_email', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_transactional', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_informative', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_cta', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_personalized', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_feedback', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_sound', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_start', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('quiet_hours_end', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('fcm_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('notification_preferences_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_preferences_pkey'))
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('ticket_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attachments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['app_users.id'], name=op.f('ticket_messages_sender_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name=op.f('ticket_messages_ticket_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_messages_pkey'))
    )
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_messages_id'), 'ticket_messages', ['id'], unique=False)
    op.drop_index(op.f('ix_signal_threads_signal_id'), table_name='signal_threads')
    op.drop_index(op.f('ix_signal_threads_post_id'), table_name='signal_threads')
    op.drop_index(op.f('ix_signal_threads_outcome'), table_name='signal_threads')
    op.drop_index('idx_signal_thread_outcome', table_name='signal_threads')
    op.drop_table('signal_threads')
    op.drop_index(op.f('ix_feature_votes_user_id'), table_name='feature_votes')
    op.drop_index(op.f('ix_feature_votes_id'), table_name='feature_votes')
    op.drop_index(op.f('ix_feature_votes_feature_request_id'), table_name='feature_votes')
    op.drop_table('feature_votes')
    op.drop_index(op.f('ix_community_reactions_user_id'), table_name='community_reactions')
    op.drop_index(op.f('ix_community_reactions_post_id'), table_name='community_reactions')
    op.drop_index(op.f('ix_community_reactions_id'), table_name='community_reactions')
    op.drop_index('idx_reaction_post_type', table_name='community_reactions')
    op.drop_table('community_reactions')
    op.drop_index(op.f('ix_user_reputation_verified_trader'), table_name='user_reputation')
    op.drop_index(op.f('ix_user_reputation_reputation_score'), table_name='user_reputation')
    op.drop_index('idx_reputation_verified', table_name='user_reputation')
    op.drop_index('idx_reputation_score', table_name='user_reputation')
    op.drop_table('user_reputation')
    op.drop_index(op.f('ix_feature_requests_vote_count'), table_name='feature_requests')
    op.drop_index(op.f('ix_feature_requests_status'), table_name='feature_requests')
    op.drop_index(op.f('ix_feature_requests_id'), table_name='feature_requests')
    op.drop_index(op.f('ix_feature_requests_created_at'), table_name='feature_requests')
    op.drop_index(op.f('ix_feature_requests_author_id'), table_name='feature_requests')
    op.drop_index('idx_feature_status_votes', table_name='feature_requests')
    op.drop_table('feature_requests')
    op.drop_index(op.f('ix_community_posts_signal_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_room_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_parent_post_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_is_deleted'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_created_at'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_author_id'), table_name='community_posts')
    op.drop_index('idx_community_posts_signal', table_name='community_posts')
    op.drop_index('idx_community_posts_room_created', table_name='community_posts')
    op.drop_index('idx_community_posts_pinned', table_name='community_posts')
    op.drop_index('idx_community_posts_author', table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_community_rooms_slug'), table_name='community_rooms')
    op.drop_index(op.f('ix_community_rooms_room_type'), table_name='community_rooms')
    op.drop_index(op.f('ix_community_rooms_is_active'), table_name='community_rooms')
    op.drop_index(op.f('ix_community_rooms_id'), table_name='community_rooms')
    op.drop_index('idx_community_rooms_active_type', table_name='community_rooms')
    op.drop_table('community_rooms')
    # ### end Alembic commands ###
